In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

In [2]:
data=pd.read_csv('test.csv')

In [3]:
data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...
1324,FDB29,NaN,Regular,0.052158,Frozen Foods,114.4176,OUT027,1985,Medium,Tier 3,Supermarket Type3
1325,FDT19,7.590,Regular,0.000000,Fruits and Vegetables,172.8080,OUT017,2007,NaN,Tier 2,Supermarket Type1
1326,DRH15,8.775,Low Fat,0.110533,Dairy,44.2428,OUT017,2007,NaN,Tier 2,Supermarket Type1
1327,FDY38,13.600,Regular,0.119176,Dairy,233.9300,OUT046,1997,Small,Tier 1,Supermarket Type1
1328,FDF14,NaN,Low Fat,0.027038,Canned,151.8340,OUT027,1985,Medium,Tier 3,Supermarket Type3